### ISSUE TITLE
Error thrown on pressing button

### ISSUE THREAD

**Issue by HashandSalt** [d4l-data4life/kirby3-static-site-generator#12]
After setting up the plugin to use the blueprint field, I get the following error after pressing the link to generate the site:

`Call to a member function code() on null`.

Kirby 3.2.2 and PHP 7.2

**Comment by jonathan-reisdorf** [comment]
Thanks for reporting! Unfortunately the current error rendering is not very specific, this could be an error while rendering one of your pages as well as an error in the plugin. That's why I've created the issue https://github.com/d4l-data4life/kirby3-static-site-generator/issues/7 which will produce more verbose errors. Once that's implemented it would be great if you could try again.

**Comment by jonathan-reisdorf** [comment]
I've reproduced the issue and created a PR (https://github.com/d4l-data4life/kirby3-static-site-generator/pull/13).
