### ISSUE TITLE
Missing Details in the Readme

### ISSUE THREAD

**Issue by tcurdt** [d4l-data4life/kirby3-static-site-generator#15]
I came across this plugin but unfortunately I don't see some details answered in the README.

1. Does the plugin require to manually trigger the rebuild of the static site?
2. Does the plugin always rebuild the complete site? What if the rebuild takes too long?
3. Is there a way to have kerby and the static site in the same document root (without a prefix)? 
```
doc
   /kerby/...
   /index.html
```

**Comment by jonathan-reisdorf** [comment]
1. This depends on your implementation. I've listed three ways to use this plugin. If you want to fully automatedly rebuild the website when something changes, you could use option
> 1) Directly (e.g. from a kirby hook)

  However, triggering the rebuild from a kirby hook will slow down any page/file changes (you would not get an instant feedback after saving your changes anymore), so I would only use it on a small site with few assets.

2. Yes, the complete site is rebuilt. Changing this behavior was already proposed here: https://github.com/d4l-data4life/kirby3-static-site-generator/issues/10 but would involve a large refactoring. In addition, the plugin would have to build a dependency tree to know which resources of what pages are used where, and then also rebuild the affected pages. That is, because you can use kirby in any way you want: You can for instance render any text from any other page on another page, and the plugin would have to understand all these references, which is an extreme challenge. Not sure if I want to go that way any time soon or at all.

3. No, this is not possible. First of all, we have to delete all files inside the folder before rebuilding, because e.g. when you delete or rename a page or file you would not want that old files lying around. This would then erase your existing kirby setup. Also, having a setup where an `index.html` lies next to an `index.php` (what of both files should your server pick? and how to get into the panel then?) would not work in most cases and does not sound like a desirable setup in my opinion. Also, the purpose of this plugin is to create an isolated file structure which can be pushed to a server without PHP or a CDN, that benefit/purpose is lost when serving the static files with kirby in the end.
