### ISSUE TITLE
Images change folder name on site generated causing Git to recommit duplicates

### ISSUE THREAD

**Issue by jonasjohansson** [d4l-data4life/kirby3-static-site-generator#3]
I don't think this is a bug but an expected behavior, but I would love it if it was possible to disable.

Running

```
return [
    'hooks' => [
        'page.update:after' => function ($page) {
            // do something before a page gets deleted
            $kirby = kirby();
            $staticSiteGenerator = new D4L\StaticSiteGenerator($kirby, $pathsToCopy = null);
            $fileList = $staticSiteGenerator->generate($outputFolder = '../docs/', $baseUrl = '/', $preserve = []);
        }
    ]
]
```

Which works well but images get a randomly named new folder each time which causes Git to want to commit the same files…

<img width="1127" alt="Screenshot 2019-06-11 at 16 07 43" src="https://user-images.githubusercontent.com/557050/59278849-1c8a7e00-8c63-11e9-8658-e84063bb153c.png">

**Comment by jonasjohansson** [comment]
I commented this out: 
      //$version->save();
and it's alright now!

**Comment by jonasjohansson** [comment]
Any way to get a clean url?

THIS
media/pages/photography/trees/myImage.jpg

INSTEAD OF THIS
media/pages/photography/trees/3026622921-1560262628/myImage.jpg

**Comment by jonathan-reisdorf** [comment]
Hi @jonasjohansson, thank you for reporting this. When commenting `$version->save()` out, there is the danger that no image at all might be generated (e.g. when the page was not previously manually visited with the browser, or when the image was changed but the page was not visited) or that the URL generated by kirby does not match the one in git. About the random number: that is a cache busting mechanism implemented in kirby's core, I need to research first if there is a way to create a more stable behavior (while still triggering the save method), but it might end up being something that needs to be fixed in kirby, not in the plugin. The same applies to your second question: It might be possible to create a "cleaner" version of the url, however at the cost of destroying the cache busting mechanism and image resizing / thumbs, which does not seem a good trade.

You can reproduce the problems I mentioned by commenting out `version->save()` but also deleting the contents of the `media` folder so that they would need to be recreated, then without loading your pages in the browser directly make a page change in the panel - the result should be that you are missing files in git.
