### ISSUE TITLE
Prompt an error when generating, after I use the modules plugin.

### ISSUE THREAD

**Issue by taoguangc** [d4l-data4life/kirby3-static-site-generator#33]
Kirby version: 2.4.4
static-site-generator version: 1.0.10
kirby-modules version: 2.0.1

When I use the modules plugin: https://getkirby.com/plugins/medienbaecker/modules
And publish some modules in one page.
Then after I click the generate button, it will display a prompt message:
```
The JSON response from the API could not be parsed. Please check your API connection.
```
If I remove the plugin folder 'kirby-modules' from the site/plugins/ directory, the generation is successful.

**Comment by jonathan-reisdorf** [comment]
Hi @taoguangc, thank you for reporting this. Unfortunately there is nothing we can do to fix this, because the modules plugin uses the `go` function here: https://github.com/medienbaecker/kirby-modules/blob/master/lib/models.php#L16 and here: https://github.com/medienbaecker/kirby-modules/blob/master/lib/models.php#L39 which causes the bug.
Kirby's `go` essentially does the following: `die(Response::redirect($url, $code));`, so, by calling `go`, the PHP process is terminated. However, for the static site generator to work, we need all pages to be rendered without redirections or and PHP needs to be kept running. Unfortunately, because of that, I have to close this issue without being able to resolve it.
