### ISSUE TITLE
CSRF Token Invalid

### ISSUE THREAD

**Issue by kabukisensei** [d4l-data4life/kirby3-static-site-generator#36]
## Expected Behavior

Generate HTML, CSS, JS, Image files for uploading to CDN

## Current Behavior

The CSRF token was invalid.
Outputs the HTML files and folder structure, but does not seem to get any CSS/Images/JS. 
Using Bulma CSS.

## Steps to Reproduce

- first ...
- then ...
- then ...

## Context
Kirby 3.5.3
v1.0.10
macOS
Manually Installed
Manually added to the home.yml blueprint and config file.

**Comment by jonathan-reisdorf** [comment]
Hi @kabukisensei, thanks for reporting. The plugin does nothing with a CSRF token so I'm guessing the issue comes from another plugin (e.g. a form plugin) or you're using a csrf token somewhere in the code. Another possibility would be that there is an issue with your panel authentication. Unfortunately I don't have enough information to work on the issue, and it's likely that it does not stem from the static site generator plugin but from somewhere else. For now I have to close the issue, but let me know if I can assist you further. In general, the concept of using a CSRF token in one of the pages won't work when generating static pages (not just with this plugin, but in general), so things like forms / submitting data to a back-end need to be solved in a different way when generating static pages, e.g. by processing the form with javascript. One more hint: Because you report that no css/images/js are generated: This indicates that the static site generator was not able to process all pages but had to stop at a particular page which caused the problem. Copying of images etc. is done after all pages are successfully generated.
