### ISSUE TITLE
Assets paths

### ISSUE THREAD

**Issue by timotheegoguely** [d4l-data4life/kirby3-static-site-generator#6]
## Expected Behavior

Every pages and subpages assets (stylesheets, js, images, etc.) should have a correct relative path. For exemple, as SiteSucker does, the stylesheet link in the root `index.html` should be:
```html
<link href="assets/css/index.css" rel="stylesheet">
```
first level folders should be:
```html
<link href="../assets/css/index.css" rel="stylesheet">
```
second level folders should be:
```html
<link href="../../assets/css/index.css" rel="stylesheet">
```
etc.

## Current Behavior

Each `index.html` pages (on every levels) have the same wrong relative assets path:
```html
<link href="/assets/css/index.css" rel="stylesheet">
```

## Possible Solution

Do I need to force absolute paths for all the assets files, or is there another solution?

## Steps to Reproduce

In my `header.php` snippet, the `css` part of the `<head>` looks like this:
```php
<?= css([
    'assets/css/index.css,
    '@auto'
]) ?> 
```

## Context

Kirby 3.2.0
kirby3-static-site-generator 1.0.2 installed manually (all the files in a plugins/static-site-generator folder)

**Comment by jonathan-reisdorf** [comment]
👋  At the moment, relative paths are not supported yet. Kirby always works with absolute paths, because it is used with a web server, and using absolute urls is the safest choice.
`/assets/css/index.css` from your example is actually an absolute path as well, it will always point to the file correctly if your website is mounted directly on `/`. If not, you need to change the base url in the configuration. Actually, what you posted under `Current Behavior` should work just fine. How are you accessing the static website? By directly opening the html file? That's not supported yet, see also https://github.com/d4l-data4life/kirby3-static-site-generator#what-doesnt-work

**Comment by jonathan-reisdorf** [comment]
(that being said, I will explore the possibility to implement an option to use relative paths later 👍)

**Comment by timotheegoguely** [comment]
Thank you for your answer. Yes I was trying to directly open html file, that's why I was confused. I didn't saw your “What doesn’t work” part, sorry.

**Comment by jonathan-reisdorf** [comment]
issue seems resolved for now, we'll explore the option of supporting relative paths later
