### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#77]
Looks like the memory is not enough.
Or maybe the programming is not perfect and the building must be done in parts?

The allowed memory size of 134217728 bytes was exhausted (tried to allocate 20480 bytes)

**Comment by Anjade** [comment]
php_value memory_limit 256M

helps, but the question is still, if the plugin walks through all pages in one go?

**Comment by Anjade** [comment]
Meanwhile, I have 500 pages in two languages; the memory needs now 512MB; I got again an error with 256MB.

**Comment by Anjade** [comment]
I try now:
php_value memory_limit 1024M
php_value max_execution_time 180

Maybe it will help.

Maybe we can divide the build somehow, please?
Maybe per top-level-pages; like: build all, build 1= x, y, z and 2 = a, b, c ... to have more than one builds for more than one parts of the system?

**Comment by jonathan-reisdorf** [comment]
This was never a problem up until latest version of Kirby. With latest version of Kirby I now get this error, too. Will debug, my suspicion is that there is a new infinite recursion issue

**Comment by jonathan-reisdorf** [comment]
The issues have been introduced with the latest changes regarding supporting kirby paginations. With version [1.10.0](https://github.com/d4l-data4life/kirby3-static-site-generator/releases/tag/1.10.0) I have now reverted that code and deprecated support for Kirby paginations. Memory issues no longer appear.
For your pagination use case you would have to create your own pagination url method instead of using Kirby's pagination method.
