### ISSUE TITLE
Default Language by getting text of children pages

### ISSUE THREAD

**Issue by Sunnyka98** [d4l-data4life/kirby3-static-site-generator#83]
I make a overview page for the next 2 generations of pages. 

## Expected Behavior

On the localhost the page render as expect in the current language.
 
I expect that the site is identical render after using the static site generater. 

## Current Behavior

The static site using the default language (german) instead of the current language (english) for the texts of the children pages. 

## Steps to Reproduce

I get a plain kit from kirby. Add some pages and the static site generator.
I made a [little repo](https://github.com/Sunnyka98/SSG-Feed) to show the error.
If you run the generator.php, an look than in the build folder to the index.html the title and text of the childeren, grand-children and grand-grand-children is in the default language.  

## Context

I use the kirby version 3.9.6, version 1.12.1 from the static-site-generater on Windows and the plugin is manually installed as submodule. I trigger the static site generator manually via script.

**Comment by jonathan-reisdorf** [comment]
Hi @Sunnyka98,

sorry for the late response, thank you for posting this bug and creating the repo for reproducing the issue.
This bug seems to have been introduced with https://github.com/getkirby/kirby/commit/de11f2a2e8598485119780ad331fa822d6ee0451
as Kirby does not support a use case where one would render a page in different languages in one row, hence these multi-language setups are a bit more unstable with this plugin (kirby updates can break the functionality). I'm working on a fix.

**Comment by jonathan-reisdorf** [comment]
Issue should be fixed with latest release 1.12.2. If that's not the case, feel free to reopen

**Comment by Sunnyka98** [comment]
Hi @jonathan-reisdorf,
The issue with the translation is fixed but now the performance is very low. I tests it with many pages (~2530)  and the time it need to render is 20x times higher than in v1.12.1. Is it possible to get a better performance?

**Comment by jonathan-reisdorf** [comment]
Hi @Sunnyka98, thank you for checking. We could do the full reset just once when switching between two languages instead of what we do now - full reset before every page render (which should not be necessary when language stays the same). I will try that out later and let you know, the next days I have a very busy schedule but hopefully there is time towards the end of the week.

**Comment by jonathan-reisdorf** [comment]
Performance should be improved with latest release 1.12.3

**Comment by paresy** [comment]
Thank you so much. Performance is back to awesome 😄
